language: java
install: true
matrix:
  include:
  - jdk: oraclejdk8
script:
  - gradle shadowJar
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$TAGPERM@github.com/RlonRyan/JBasicX --tags
  - ls -R
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Prb+lQhG5TGehm8UNRyEHbmhdbWnbaaf2yo5W2fxbmbQLrn585AjbfsDhy8EaWCTixxr/ESPQQ6txoh5+9xVdwQgx8H1zK2dWvCq2Qqw5Y3yGHZr0Q8ncJDp8sWWHqDG51GyuEJOqWeUrGVj7r4k4NLpdqanJfWJadXgzbKlvGV5ECD3DRkwmTvP9nzwO/cop/wObWBdao/Bc7Xx4WR/5uvAWGtRwlBeDiwBnOR1QSaP8bnTOkRcz3w6cRZ/5vL9jf6jKmH3URB4DYmri827CH/TLJl9QfIMH/s+byBO6Ma+iQd8UkeHXqIHkpBrGOBa1FleC5u8JpOQtk0GGR20MBIjSGv9rVE+CnbfF0T1wvMRJjnwdNvSy/7+v0h6YsqbEs0kqijSyPFw0PFmRVK2TGr4OHoIcumptmg7m4zxjAuLAo+YCMMdVN8h0fPIJJslWH3LLjtIwBGeLbX9F8+6n9j9KXAkYb1ajNhgRafHS5++9aCvM1gWi+QKd7GvcbTz8bVNjJeHiu4nJGHBU7imGmqAps3PqR8dHC/X+lzen/59TxVRS66wGgXccLKHNSJkxUEM5hUYIkfWlvxaGd0OJHxtl93Mbd4vgh6V9tbAg776AuigqR1RTLRKs9auZR3SKrx8SONLoMLkWNHGgimdLnfwW6kAcvlBitVhTrHiOpc=
  file: 
    - "/build/libs/LogitowBridge-0.3-all.jar"
    - "README.md"
  on:
    repo: itsMatoosh/logitow-bridge
    tags: false
    all_branches: true
